apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "nico-machine-a-tron.name" . }}-certificate
  namespace: {{ include "nico-machine-a-tron.namespace" . }}
  labels:
    {{- include "nico-machine-a-tron.labels" . | nindent 4 }}
spec:
  {{- $bmcMockDns := printf "%s-bmc-mock.%s.svc.cluster.local" (include "nico-machine-a-tron.name" .) (include "nico-machine-a-tron.namespace" .) }}
  {{- $extraDns := prepend (.Values.certificate.extraDnsNames | default list) $bmcMockDns }}
  {{- $certWithExtra := merge (dict "extraDnsNames" $extraDns) .Values.certificate }}
  {{- include "nico-machine-a-tron.certificateSpec" (dict "name" (printf "%s-certificate" (include "nico-machine-a-tron.name" .)) "svcName" (include "nico-machine-a-tron.name" .) "namespace" (include "nico-machine-a-tron.namespace" .) "cert" $certWithExtra "global" .Values.global) | nindent 2 }}
